In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
data = pd.read_csv('.\Titanic-Dataset.csv')

In [3]:
#Q1) Load the dataset and inspect it thoroughly
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
#Q2) Answer in code: How many nulls per column?
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
#Q3) What is the survival rate by gender?
survived_male_rate = len(data[(data['Survived'] == 1) & (data['Sex'] == 'male')])/len(data)
print("Male survival rate is", survived_male_rate)

survived_female_rate = len(data[(data['Survived'] == 1) & (data['Sex'] == 'female')])/len(data)
print("Female survival rate is", survived_female_rate)

Male survival rate is 0.122334455667789
Female survival rate is 0.2615039281705948

In [6]:
#Q4) What is the average age of survivors vs non-survivors?
survivors = int(data[data['Survived'] == 1]['Age'].mean())
non_survivors = int(data[data['Survived'] == 0]['Age'].mean())

In [7]:
#Q5) Fill missing Age with median age grouped by Pclass
data.groupby('Pclass').agg({'Age':np.median}).reset_index()

C:\Users\Sunny\AppData\Local\Temp\ipykernel_10448\1708257759.py:2: FutureWarning: The provided callable <function median at 0x0000024CC3B6BA60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  data.groupby('Pclass').agg({'Age':np.median}).reset_index()

   Pclass   Age
0       1  37.0
1       2  29.0
2       3  24.0

In [8]:
#Q6) Drop the Cabin column and write a comment explaining why
data.drop(columns = ['Cabin'], inplace = True)
data.head()

#The column cabin has too many nulls and it would add any additional information for the ML model

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S